wandb:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: "trust-analysis-tsr"
  name: ${task_name}
  group: ""
  tags: ${tags}
  job_type: ""
  log_model: "all" # Upload all checkpoints to W&B as artifacts
