# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - datamodule: gtsrb
  - model: resnet18
  - callbacks: default
  - logger: wandb
  - trainer: default
  - paths: default
  - metrics/severity: default


task_name: "train"

tags: ["dev", "baseline"]

# path to data directory
data_dir: ./data/

# path to checkpoint for evaluation/resumption
ckpt_path: null
